name: Build

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
#  branches: 
#    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
    build:
        name: Building
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false

        steps:
            - name: Setup cmake
              uses: jwlawson/actions-setup-cmake@v1.13.0

            - name: Setup arm-none-eabi-gcc
              uses: fiam/arm-none-eabi-gcc@v1
              with:
                release: '10-2020-q4'

            - name: Clone repo
              uses: actions/checkout@v3
              with:
                ref: ${{ github.event.client_payload.branch }}

            - name: Get short sha1
              id: short_sha1
              run: echo "value=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

            - name: Build
              run: |
                    mkdir build output
                    git submodule update --init
                    cd 3rdparty/pico-sdk
                    git submodule update --init
                    cd ../../build
                    cmake -DPICO_BOARD=bbq20kbd_breakout -DCMAKE_BUILD_TYPE=Debug ..
                    make
                    cp app/i2c_puppet.{bin,elf,uf2} ../output
            - name: Upload package artifact
              uses: actions/upload-artifact@v1
              with:
                path: output
                name: i2c_puppet-bbq20kbd_breakout-${{ steps.short_sha1.outputs.value }}
